### PR TITLE
Replace globule with micromatch

### PR DESCRIPTION
**Pull request by TrySound**
multimatch do the same but it's not dead and doesn't have deprecated dependencies.

### CODE REVIEW

**Comment by phated** [comment]
I'd prefer something based on micromatch so we have the same globbing modules throughout the gulp dependency tree.  Could you send a PR to multimatch updating to use that library?

**Comment by TrySound** [comment]
@phated Why? micromatch supports multiple patterns. We can use it directly.

**Comment by TrySound** [comment]
Heh. Even API similar :)

**Comment by phated** [comment]
Good catch, I didn't know that :+1:

**Comment by phated** [comment]
Please rebase out the multimatch commit

**Comment by TrySound** [comment]
@phated  Patch release?

**Comment by phated** [comment]
Looks good.  Thanks

**Comment by phated** [comment]
Published.  Thanks again.

**Pull request merged**
